### ISSUE TITLE
Just get a black circle in IB

### ISSUE THREAD

**Issue by malcolmhall** [CardinalNow/iOS-CircleProgressView#17]
Using Objc version and Xcode 6.4. When adding a UIView and setting the class to CircleProgressView it just displays a black circle and its not possible to recreate the blue and grey track colours shown in the readme.

**Comment by xrolfex** [comment]
Using Xcode 6.4 and the Obj-C version I was able to recreate it. The problem is there was not a prepareForInterfaceBuilder to sent the default IBValues, even without that you can select the values in the inspector to recreate the readme. I will be committing the Obj-C version with the updated prepareForInterfaceBuilder shortly.
<img width="1552" alt="screen shot 2015-07-22 at 7 28 21 pm" src="https://cloud.githubusercontent.com/assets/1327947/8839962/1f0faf84-30a9-11e5-9dbf-916b04fb39fc.png">
