### ISSUE TITLE
Swift 3.0 support

### ISSUE THREAD

**Issue by run4jit** [CardinalNow/iOS-CircleProgressView#36]
Is this library support for swift 2.0?

**Comment by lfarah** [comment]
Would also love to see it working in Xcode 8

**Comment by markogley** [comment]
I have a copy of it working for Xcode 8. I changed all the CG methods and UIColor methods that were causing issues but I am not sure where to put because Swift 3.0 is so new.
[CircleProgressView.swift.zip](https://github.com/CardinalNow/iOS-CircleProgressView/files/491424/CircleProgressView.swift.zip)

**Comment by xrolfex** [comment]
Merged in. Creating new pod spec now.

**Comment by sochalewski** [comment]
@xrolfex Why current .podspec requires minimum iOS 9.0? Is it necessary or could be decreased easily?

**Comment by xrolfex** [comment]
@sochalewski Updated pod spec to support iOS 8 with swift 3.0. Spec version: 1.0.13
