### ISSUE TITLE
Using CircleProgressView in my app

### ISSUE THREAD

**Issue by stevenabreu7** [CardinalNow/iOS-CircleProgressView#57]
Hello,

great job on the progress view, I really love it. I used it in a small interval timer app. Do I have your permission to publish the app (using your CircleProgressView) to the AppStore? The app will be free and I don't plan on making any money with it, it should only act as a portfolio for future job applications as I am a student looking for internships.

Looking forward to hearing back from you,
Steve

**Comment by supersaiyen** [comment]
Steve,
We've released this component under the MIT license, feel free to use it
however you like. We're glad to hear you like it.
Thanks,
Rusty


On Aug 14, 2017 4:55 AM, "Steven Abreu" <notifications@github.com> wrote:

Hello,

great job on the progress view, I really love it. I used it in a small
interval timer app. Do I have your permission to publish the app (using
your CircleProgressView) to the AppStore? The app will be free and I don't
plan on making any money with it, it should only act as a portfolio for
future job applications as I am a student looking for internships.

Looking forward to hearing back from you,
Steve

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/CardinalNow/iOS-CircleProgressView/issues/57>, or mute
the thread
