### ISSUE TITLE
ui issue

### ISSUE THREAD

**Issue by lazyjean** [CardinalNow/iOS-CircleProgressView#67]
1. drag an UIView to storyboard
2. set class CircleProgressView
3. set Progress property to 1.0
3. tun Rounded Cap on

**Comment by xrolfex** [comment]
What is the issue?

**Comment by farshadmb** [comment]
@xrolfex track cap and background cap layer overlap eachother

**Comment by mattstrong** [comment]
@xrolfex Can this be fixed?

**Comment by xrolfex** [comment]
It can be fixed but it would require the a significant change in the structure. Essentially the fill track needs its percentage to be larger when track cap is set. At the moment it time i will put it in the backlog to work. On Going to close this issue for now.

**Comment by KevinQuisquater** [comment]
@xrolfex any updates on this issue, by any chance?

Just to clarify the problem, since the issue is badly formatted: if rounded cap is enabled and the track path has a background color, when progress is around 99%-100%, the line overlaps with itself and the rounded arc takes the color of the progress path background, rather than the progress path fill color.

Here's a [screenshot](https://i.imgur.com/KxUnmhy.png) at 100%.
